package com.bhoruka.bloodbank.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "Patient")
public class Patient {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String patientName;

    @DynamoDBAttribute
    private String reasonOfTransfusion;

    @DynamoDBAttribute
    private Integer age;

    @DynamoDBAttribute
    private String gender;

    @DynamoDBAttribute
    private String registrationNumber;

    @DynamoDBAttribute
    private String roomWardNumber;

    @DynamoDBAttribute
    private String bedNumber;

    @DynamoDBAttribute
    private String natureOfOperation;

    @DynamoDBAttribute
    private String cabinNumber;

    @DynamoDBAttribute
    private String hospital;

    @DynamoDBAttribute
    private String bloodGroup;

    @DynamoDBAttribute
    private String rhD;

    @DynamoDBAttribute
    private String consultant;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String bloodGroupAndSegmentSaved;

    @DynamoDBAttribute
    private Date bloodDetailsDate;

    @DynamoDBAttribute
    private Integer wholeBlood;

    @DynamoDBAttribute
    private Integer concRbc;

    @DynamoDBAttribute
    private Integer plasmaFfp;

    @DynamoDBAttribute
    private Integer plateletConcPrp;

    @DynamoDBAttribute
    private Integer cryoF8;

    @DynamoDBAttribute
    private Integer cryofreeGranulocyte;

    @DynamoDBAttribute
    private Integer unit;

    @DynamoDBAttribute
    private String labNumber;

    @DynamoDBAttribute
    private Date dateOfCollection;

    @DynamoDBAttribute
    private Date dateOfExpiry;

    @DynamoDBAttribute
    private String modeOfPayment;

    @DynamoDBAttribute
    private Long receivedSumOfRupees;

    @DynamoDBAttribute
    private Date transfusionDate;
}
